### ISSUE TITLE
Issue with migrations - Could not find generator 'shopr:install:migrations'.

### ISSUE THREAD

**Issue by craft37** [shoprgem/shopr#20]
rails generate shopr:install:migrations --trace
Running via Spring preloader in process 25203
Could not find generator 'shopr:install:migrations'. Maybe you meant 'active_record:migration', 'migration' or 'test_unit:integration'

ruby 2.3.0

**Comment by wgriffiths** [comment]
I think shopr:install:migrations has been removed.  Worked for me if i just skip 
rails generate shopr:install:migrations

**Comment by lxiaodao** [comment]
View readme of the tag 1.1.2.
The shopr gem is 1.1.2 but is not the same as master branch.
